config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :users
  post '/attendances/:id', to: 'events#attending', as: 'attendee'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'welcome#index'# :path_prefix => '/:username'
  root 'users#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'login' => 'logins#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :event_id, uniqueness: { scope: :user_id }
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  has_many :attendances
  has_many :users, through: :attendance, dependent: :destroy
  belongs_to :creator, class_name: 'User'

  scope :today, -> { where('date == ?', Date.today) }
  scope :upcoming, -> { where('date > ?', Date.today) }
  scope :previous, -> { where('date < ?', Date.today) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, presence: true
  has_many :attendances
  has_many :events, through: :attendances
  has_many :own_events, foreign_key: 'creator_id', class_name: 'Event'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :user_login, except: %I[index show]
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    @users = User.all
    @today = Event.today
    @upcoming = Event.upcoming
    @previous = Event.previous
  end

  # GET /events/1
  # GET /events/1.json
  def show
    set_event
    @users = User.all
    @user = User.find(@event.creator.id)
    @attendees = Attendance.where(event_id: @event.id)
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit; end

  def attending
    set_event
    @attendee = Attendance.new
    @attendee.event_id = @event.id
    @attendee.user_id = current_user.id
    @attendee.save
    redirect_to @event
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :date, :datetime, :creator_id)
  end

  def user_login
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.where(username: params[:username])
    if @user.empty? == false
      session[:user_id] = @user[0].id
      redirect_to root_path
    else
      redirect_to '/login'
    end
  end

  def login; end

  def welcome; end

  def destroy
    session.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def log_or_not
    log_status = []
    if logged_in?
      log_status [0] = link_to 'Log Out', logout_path, method: :delete
    else
      log_status [0] = link_to 'Log in', '/login'
      log_status [1] = link_to 'Create User', new_user_path
    end
    log_status
  end

  def log_for_event
    log_status = []
    if logged_in?
      log_status [0] = link_to 'New event', new_event_path
      log_status [1] = link_to 'View all events', events_path
    else
      log_status [0] = link_to 'View all events', events_path
    end
    log_status
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def user
    if current_user
      link_to current_user.username, user_path(current_user)
    else
      'Please Sign In.'
    end
  end

  def new_event
    link_to 'New Event', new_event_path if current_user
  end

  def index_empty_table
    if @events.empty?
      'There are not events created yet'
    else
      render 'table'
    end
  end

  def event_list(table)
    return 'There are not events.' if table.empty?

    if table == @today
      render 'today_event'
    elsif table == @upcoming
      render 'upcoming_event'
    else
      render 'past_event'
    end
  end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user_log
    if logged_in?
      current_user.username
    else
      'you are not logged in'
    end
  end

  def empty_table
    if @user.own_events.empty?
      'There are no events jet'
    else
      render 'own_table'
    end
  end

  def empty_attending_table
    if @user.events.empty?
      'There are no events register jet'
    else
      render 'attend_events'
    end
  end

  def empty_attended
    if @user.events.previous.empty?
      'No events have been attended'
    else
      render 'attended'
    end
  end

  def empty_today
    if @user.events.today.empty?
      'There are no events for today'
    else
      render 'today_events'
    end
  end

  def user_own_events
    @user.own_events
  end

  def past_events_user
    @user.events.previous
  end

  def future_events_user
    @user.events.upcoming
  end

  def today_events_user
    @user.events.today
  end
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :date %>
    <%= f.hidden_field :creator_id, :value => current_user.id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/_past_event.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @previous.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
        <td><%= event.date %></td>
        <td><%= event.created_at.to_date %></td>
        <td><%= event.creator.username %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
        <td><%= event.date %></td>
        <td><%= event.created_at.to_date %></td>
        <td><%= event.creator.username %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_today_event.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @today.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
        <td><%= event.date %></td>
        <td><%= event.created_at.to_date %></td>
        <td><%= event.creator.username %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_upcoming_event.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcoming.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.body %></td>
        <td><%= event.date %></td>
        <td><%= event.created_at.to_date %></td>
        <td><%= event.creator.username %></td>
        <td><%= link_to 'Show', event %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Signed in as: <%= user %></h3>

<h1>All Events</h1>

<%= index_empty_table %>

<br><br>

<%= new_event %>

<h2>Today's Events</h2>
<%= event_list(@today) %>
<h2>Upcoming Events</h2>
<%= event_list(@upcoming) %>
<h2>Past Events</h2>
<p><%= event_list(@previous) %></p>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @event.body %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>
<p>
  <strong>Attendees:</strong>
  <ol>
    <% @attendees.where(event_id: @event.id).each do |i|%>
      <li>
       <p>User Name: <%= @users.find(i.user_id).username %> <br/></p>
      	<p>Email: <%= @users.find(i.user_id).email %></p>
      </li>
    <% end %>
  </ol>
</p>

<%= link_to 'Attend', attendee_path(@event), method: :post %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Associate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= log_or_not[0] %>
      <%= log_or_not[1] %>
    <%= yield %>
      <%= log_for_event[0] %>
      <%= log_for_event[1] %>
  </body>
</html>

app/views/logins/new.html.erb
<p id=”alert”><%= alert %></p>
<h1>Login</h1>
<%= form_tag logins_path do |form| %>
  <div class=”field”>
    <%= label_tag :Username %>
    <%= text_field_tag :name %>
  </div>
  <div class=”actions”>
    <%= submit_tag 'Login' %>
  </div>
<% end %>

app/views/users/_attend_events.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% future_events_user.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.body %></td>
      <td><%= event.date %></td>
      <td><%= event.created_at.to_date %></td>
      <td><%= event.creator.username %></td>
      <td><%= link_to 'Show', event %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/_attended.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% past_events_user.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.body %></td>
      <td><%= event.date %></td>
      <td><%= event.created_at.to_date %></td>
      <td><%= event.creator.username %></td>
      <td><%= link_to 'Show', event %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_own_table.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @own_events.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.body %></td>
      <td><%= event.date %></td>
      <td><%= event.created_at.to_date %></td>
      <td><%= event.creator.username %></td>
      <td><%= link_to 'Show', event %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/_today_events.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Date</th>
      <th>Creation date</th>
      <th>Creator</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% today_events_user.each do |event| %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.body %></td>
      <td><%= event.date %></td>
      <td><%= event.created_at.to_date %></td>
      <td><%= event.creator.username %></td>
      <td><%= link_to 'Show', event %></td>
    </tr>
  <% end %>
</tbody>
</table>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<h2><%= current_user_log %></h2>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/logins.html.erb
<p id="notice"><%= notice %></p>

<h1>Sign in to see the Events</h1>
<%= form_for(@user,  url: "/access", method: :post) do |form| %>
  <div class="field">
    <%= form.label :name, "Enter your name" %><br><br>
    <%= form.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= form.label :email, "Enter your email" %><br><br>
    <%= form.text_field :email %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Sign In'%>
  </div>
<% end %>


<br>

New To the page? <b><%= link_to 'Create a New User', new_user_path %></b>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <p>
    <strong>Username:</strong>
    <%= @user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Home', root_path %>
</div>
<h2> These are <%= @user.username %>'s events </h2>
<% user_own_events.each do |e| %>
  <p><%= e.title %></p>
  <p><%= e.body %></p>
  <p><%= e.date %></p>
<% end %>

<h2>Today's events</h2>
<%= empty_today %>
<h2>Future events</h2>
<%= empty_attending_table %>
<h2>Past Events </h2>
<%= empty_attended %>

<%= link_to 'Events', events_path %>